export const FULLNAME = "fullName"
export const BIRTHDATE = "birthDate"
export const EMAIL = "email"
export const PHONE_NUMBER = "phone"
export const GENDER = "gender"
export const GRADE_ID = "gradeId"
export const CLASS_ID = "classId"
export const IMAGE_PATH = "imagePath"
export const FILES = "files"

